[package]
name = "NagatoInterpreter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "NagatoInterpreter"
path = "src/main.rs"

[dependencies]
regex = "1.7"
core = { path = "./core" }
petgraph = "0.6.5"
